const missingSummary = { status: "missing" } as const;

export const CONTEXT_RECORDS_V1_SNAPSHOT = {
  activeTask: {
    kind: "response",
    request: {
      contextItems: [
        {
          filePath: "src/index.tsx",
          id: "file:src/index.tsx",
          schemaVersion: 1,
          summaryState: missingSummary,
          type: "file",
        },
        {
          createdAt: 20,
          id: "request-context:20",
          output: "active request context answer",
          prompt: "Earlier request context",
          schemaVersion: 1,
          sourceRequestId: 20,
          summaryState: missingSummary,
          type: "llm-response",
        },
      ],
      focusedContextItemId: "request-context:20",
      id: 21,
      patchProgress: {
        files: [{ operation: "update", path: "src/index.tsx" }],
        patchCharacterCount: 321,
      },
      question: "Resume this request",
      responseText: "resumed response output",
      status: "done",
    },
  },
  nextContextItemId: 1,
  nextLlmRequestId: 1,
  schemaVersion: 1,
  workspace: {
    composer: { cursorPosition: 0, message: "" },
    contextItems: [
      {
        filePath: "src/index.tsx",
        id: "file:src/index.tsx",
        schemaVersion: 1,
        summaryState: missingSummary,
        type: "file",
      },
      {
        createdAt: 2,
        id: "response:2",
        output: "saved response output",
        prompt: "Explain context records",
        schemaVersion: 1,
        sourceRequestId: 2,
        summaryState: missingSummary,
        type: "llm-response",
      },
      {
        createdAt: 3,
        id: "shell:3",
        result: {
          command: "bun test",
          durationMs: 12,
          exitCode: 0,
          stderr: "",
          stdout: "390 pass",
          timedOut: false,
          truncated: false,
        },
        schemaVersion: 1,
        sourceRequestId: 3,
        summaryState: missingSummary,
        type: "shell-command-output",
      },
      {
        createdAt: 4,
        id: "say:4",
        schemaVersion: 1,
        summaryState: missingSummary,
        text: "literal user note",
        type: "user-text",
      },
      {
        createdAt: 5,
        errorMessage: "Interrupted request fixture",
        id: "live:5",
        output: "partial response",
        prompt: "Interrupted prompt",
        schemaVersion: 1,
        sourceRequestId: 5,
        status: "error",
        summaryState: missingSummary,
        type: "llm-response-live",
      },
      {
        blocks: [
          {
            id: "agent-message:6",
            kind: "stream",
            streamKind: "assistant",
            text: "agent completed the review",
            timestamp: 6,
          },
        ],
        createdAt: 6,
        id: "agent:6",
        mode: "edit",
        prompt: "Review context records",
        sandbox: {
          baselineTree: "abc123",
          diffStatus: "dirty",
          path: "/tmp/clutch-agent",
          root: "/repo",
          summary: "agent changed one file",
        },
        schemaVersion: 1,
        sessionAvailability: "live",
        status: "idle",
        summaryState: missingSummary,
        type: "pi-agent",
      },
      {
        createdAt: 7,
        diffText: "diff --git a/src/a.ts b/src/a.ts\n-old\n+new",
        id: "diff:7",
        prompt: "Update a",
        proposal: {
          patch:
            "*** Begin Patch\n*** Update File: src/a.ts\n@@\n-old\n+new\n*** End Patch",
          summary: "Update a",
        },
        schemaVersion: 1,
        sourceRequestId: 7,
        summary: "Update a",
        summaryState: missingSummary,
        type: "diff",
      },
      {
        createdAt: 8,
        diffText: "diff --git a/src/b.ts b/src/b.ts\n-old\n+new",
        id: "agent-diff:8",
        prompt: "Agent update b",
        schemaVersion: 1,
        sourceAgentItemId: "agent:6",
        summary: "Update b",
        summaryState: missingSummary,
        type: "agent-sandbox-diff",
      },
    ],
    focusedContextItemId: "diff:7",
  },
  workspaceRoot: "/repo",
} as const;

export const LEGACY_DIFF_V1_RECORD = {
  createdAt: 9,
  diffText: "diff --git a/src/legacy.ts b/src/legacy.ts\n-before\n+after",
  id: "diff:9",
  prompt: "Legacy update",
  proposal: {
    edits: [{ newText: "after", oldText: "before", path: "src/legacy.ts" }],
    summary: "Legacy update",
  },
  schemaVersion: 1,
  sourceRequestId: 9,
  summary: "Legacy update",
  summaryState: {
    sourceHash: "pending-hash",
    status: "pending",
    workerId: "worker:legacy",
  },
  type: "diff",
} as const;
